const main = ()=>{
  try{
    codigo;
  }catch(erro){
    console.error(`Deu erro no código. E o erro é esse: \n\n ${erro}`);
  }
}
main();